# configurations 

GLOBAL:
  url: "http://**1**/**2**{}"
    # 1: url of the target websire
    # 2: novel specifier
  start: 1068616
  pages: 15
    # these 2 make up the number to fill in the bracket above in url

WEB:
  key: "class"
    # class, id, etc. Inspect the webpage for details
  val: "novelinfvie"
    # same as above

OUT: "output.txt"
    # name of the output .txt file